name: Build check and release if on main

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    # Reference your environment variables
    environment: cargo

    steps:
      - uses: actions/checkout@master
        with:
          # get git tags info
          fetch-depth: 0

      - name: Get current version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n 1 | sed -E 's/version = "(.*)"/\1/')
          echo "cargo_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check version against latest git tag
        id: version_check
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          if [ "v${{ steps.get_version.outputs.cargo_version }}" == "$LAST_TAG" ]; then
            echo "Version has not been bumped. Exiting..."
            exit 1
          fi

      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
